version: "3"
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.17.7
    network_mode: host
    restart: always
    env_file:
      - elasticsearch.env
    volumes:
      - /docker/elasticsearch/data:/usr/share/elasticsearch/data
      - /docker/elasticsearch/plugins:/usr/share/elasticsearch/plugins
  dht-server-full-1: &dht-server
    image: zpqsunny/dht-server-full:latest
    build:
      context: dht-server
      dockerfile: Dockerfile
    network_mode: host
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "20m"
    environment:
      - PORT=6881
  dht-server-full-2:
    <<: *dht-server
    environment:
      - PORT=6882
  dht-server-full-3:
    <<: *dht-server
    environment:
      - PORT=6883
  mongo:
    container_name: mongo
    image: mongo:7
    volumes:
      - /docker/mongo/db:/data/db
      - /docker/mongo/backup:/backup
    command: mongod --shardsvr --replSet shareA --bind_ip_all --port 27018 --oplogMinRetentionHours 3
    env_file:
      - mongo.env
    network_mode: host
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "20m"
  dht-es:
    depends_on:
      - mongo
    image: zpqsunny/dht-es:latest
    build:
      context: dht-es
      dockerfile: Dockerfile
    network_mode: host
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "20m"
    env_file:
      - dht-mongo.env
      - dht-elasticsearch.env