version: "3"
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.17.7
    network_mode: host
    restart: unless-stopped
    env_file:
      - ./es.env
    volumes:
      - /docker/elasticsearch/data:/usr/share/elasticsearch/data
      - /docker/elasticsearch/plugins:/usr/share/elasticsearch/plugins
  redis:
    container_name: redis
    image: zpqsunny/dht-redis:latest
    volumes:
      - /docker/redis:/data/
    network_mode: host
    restart: unless-stopped
    user: root
  dht-server-1: &dht-server
    depends_on:
      - redis
    image: zpqsunny/dht-server:latest
    build:
      context: dht-server
      dockerfile: Dockerfile
    network_mode: host
    restart: unless-stopped
    env_file:
      - ./redis.env
    environment:
      - PORT=6881
  dht-server-2:
    <<: *dht-server
    environment:
      - PORT=6882
  dht-server-3:
    <<: *dht-server
    environment:
      - PORT=6883
  mongo:
    container_name: mongo
    image: mongo:4.4.1
    volumes:
      - /docker/mongo/db:/data/db
      - /docker/mongo/backup:/backup
    command: mongod --shardsvr --replSet shareA --bind_ip 0.0.0.0 --port 27018
    env_file:
      - ./mongo.env
    network_mode: host
    restart: unless-stopped
  dht-peer:
    depends_on:
      - redis
      - mongo
    deploy:
      mode: replicated
      replicas: 3
    image: zpqsunny/dht-peer:latest
    build:
      context: dht-server
      dockerfile: Dockerfile
    network_mode: host
    restart: unless-stopped
    volumes:
      - /metadata:/metadata
    env_file:
      - ./dht-mongo.env
      - ./redis.env
  dht-es:
    depends_on:
      - mongo
    image: zpqsunny/dht-es:latest
    build:
      context: dht-es
      dockerfile: Dockerfile
    network_mode: host
    restart: unless-stopped
    env_file:
      - ./dht-mongo.env
      - ./dht-es.env