name: DHT auto build
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v5
      - name: Build with Maven
        run: |
          mvn -Dfile.encoding=UTF-8 -DskipTests=true install
          mvn -Dmaven.multiModuleProjectDirectory=./dht-server -Dfile.encoding=UTF-8 -DskipTests=true package
          mvn -Dmaven.multiModuleProjectDirectory=./dht-peer -Dfile.encoding=UTF-8 -DskipTests=true package
          cp ./dht-server/target/dht-server-1.0-SNAPSHOT-jar-with-dependencies.jar ./dht-server-${{ steps.branch-name.outputs.current_branch }}.jar
          cp ./dht-peer/target/dht-peer-1.0-SNAPSHOT-jar-with-dependencies.jar ./dht-peer-${{ steps.branch-name.outputs.current_branch }}.jar
          zip -q -r release.zip *.jar
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.branch-name.outputs.current_branch }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./release.zip
          asset_name: release-${{ steps.branch-name.outputs.current_branch }}.zip
          asset_content_type: application/zip
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push dht-server
        uses: docker/build-push-action@v2
        with:
          content: dht-server
          push: true
          tags: zpqsunny/dht-server:latest,zpqsunny/dht-server:${{ steps.branch-name.outputs.current_branch }}
      - name: Build and push dht-peer
        uses: docker/build-push-action@v2
        with:
          content: dht-peer
          push: true
          tags: zpqsunny/dht-peer:latest,zpqsunny/dht-peer:${{ steps.branch-name.outputs.current_branch }}
